### ISSUE TITLE
Check use of `cluster()` vs. `vce()`

### ISSUE THREAD

**Issue by jmshapir** [JMSLab/xtevent#12]

**Comment by jorpppp** [comment]
This bug arises because `ivreghdfe` does not allow specifying different ways to compute standard errors with `vce`. Instead, it only allows `cluster()` or `robust`. @Constantino-Carreto-Romero will change the code upstream such that if the user writes `vce(cluster x)` when using xtevent for IV estimation and reghdfe, `xtevent` will parse the option and pass it to `ivreghdfe` as `cluster(x)`. 

This can be done either breaking the options string into words, or using regular expressions.

**Comment by jorpppp** [comment]
Summary: In this issue we allowed the user to specify `vce` to obtain standard errors even when using `ivreghdfe' 

Thread continues in #19
