### ISSUE TITLE
Obtaining the regular DiD estimates implied by the model

### ISSUE THREAD

**Issue by izmartinez** [JMSLab/xtevent#16]
It would be useful if one could also obtain the regular DiD estimates implied by the model. This is not straight forward to do manually when the option -trend- is used (and likely also not with other options allowed by -xtevent-).

**Comment by jorpppp** [comment]
Thank you @izmartinez ! Just to clarify, by the regular DiD estimates, do you mean "static" Diff in Diff estimates like those produced with the "static" option in settings without trend adjustment?

**Comment by izmartinez** [comment]
Sorry, only saw that you replied now.
No, I meant the DiD that measures the average effect over the entire post-treatment period. Without the trend option, this is the static DiD. But shouldn't it also be possible to compute the DiD estimator while still controlling for pre-trends as the trend option does?

**Comment by jorpppp** [comment]
If we understand @izmartinez 's request correcly here, what we should do is to be able to average the event-time coefficients after the event (those labeled with _k_eq_p* in the output), and subtract from that average the average of the event-time coefficients before the event (those labeled with _k_eq_m* in the output). This difference should be equivalent to a static DD estimate. Maybe there are some weighting issues that @jorpppp will figure out.

To start working on this, @rayhuang11 will

- [ ] Implement the subtraction on averages in `_eventols.ado`
- [ ] Become familiar with the `lincom` Stata command. We'll need it to get the standard errors of this DD estimate. 

@Constantino-Carreto-Romero  can help if needed.

**Comment by jorpppp** [comment]
@rayhuang11  will keep working on this. Maybe using `lincom` we won't need to calculate the difference through averages. In any case, the point estimate from `lincom` and the estimate using the averages should match.

The output from `lincom` is fine.

**Comment by rayhuang11** [comment]
@jorpppp @Constantino-Carreto-Romero thanks for the help so far.

I implemented both approaches, both of which are included in https://github.com/JMSLab/xtevent/commit/84b7b57cf804da8dd5ddd2e8ef5f1be2f5b287ac. The two estimates match. Here is what the output looks like. The first one is from the matrixes; the second one is from `nlcom`. 

<img width="949" alt="Screen Shot 2022-06-29 at 3 42 15 PM" src="https://user-images.githubusercontent.com/106756436/176524834-61954831-3d3c-4f2d-b193-69a63616dfe2.png">

I used `nlcom` instead of `lincom` because `lincom` did not like the division component of the DiD calculation. I think this might be a error on the part of lincom, as it seems to be recognizing the `window` local as a coefficient. I might be able to get around, but nlcom worked so I went with that for now. I assumed which one I use does not impact the results.

If we prefer to just use the `nlcom` approach, let me know, and I will make the adjustment, amend the help file, and create a pull request.

Thanks!

**Comment by Constantino-Carreto-Romero** [comment]
@rayhuang11 it looks good. What about adding the option `noheader` to `nlcom`? Maybe it would be good to suppress showing the linear combination.

**Comment by jorpppp** [comment]
We'll remove the `noheader` option because `lincom` doesn't allow it. 
Get rid of the matrix stuff and just use `lincom`.

**Comment by rayhuang11** [comment]
@jorpppp @Constantino-Carreto-Romero thanks for your help! We are ready to merge.

**Comment by rayhuang11** [comment]
@jorpppp done! What do you think of the help file? Let me know if you have any suggestions. Thanks.

**Comment by rayhuang11** [comment]
@jorpppp thanks!

Currently, if I try to run both `static` and `staticDD` simultaneously, I get the following error: "option staticDD not allowed". Is this sufficient?

Alternative name ideas for `staticDD`:

- `dd`
- `diffdiff`, which can be abbreviated as `diff`
- `diffavg`

**Comment by jorpppp** [comment]
@rayhuang11 Yes, the error message works.

As of option names, I like `diffavg`. Can you change the files to use that option name, please?

**Comment by rayhuang11** [comment]
@jorpppp sure thing. How do we feel about `diff` as an abbreviation?

**Comment by jorpppp** [comment]
Summary: In this issue we added functionality to obtain the difference in the average of the post-event coefficients and the average of the pre-event coefficients.

We'll work out issues when the sample is unbalanced in #65.

Thread continues in #63.
