### ISSUE TITLE
Allow replacing when saving event-time dummies

### ISSUE THREAD

**Issue by jorpppp** [JMSLab/xtevent#177]
Allow replacing when saving event-time dummies.

**Comment by Constantino-Carreto-Romero** [comment]
@jorpppp 
- in https://github.com/JMSLab/xtevent/commit/5e020902f73ce5712072791ca5870399846edae4 I implemented the `replace` suboption. Previously, the error message that was shown was raised because the program tried to save the new variables, something like `variable x already defined`. Therefore, I added a check issuing an error message if there are event-time dummy variables with the `stub` prefix and recommending using the replace suboption.
- in https://github.com/JMSLab/xtevent/commit/a6f5347dbf6c714a76066bf856a01ed6c8229111 I uploaded a file with examples to test the suboption.
- in https://github.com/JMSLab/xtevent/commit/95662b9c160fc1131652414dfa13f6c07810244a I updated the help file.
- and in https://github.com/JMSLab/xtevent/commit/3548c5aa46542438eb932abb8f18d69f640a365e I added an example to the test file. Then, I run the test file without inconvenience.

**Comment by jorpppp** [comment]
Thanks @Constantino-Carreto-Romero , looks good. I'll start a PR to review.

**Comment by Constantino-Carreto-Romero** [comment]
Changes in this issue were merged to main by the PR https://github.com/JMSLab/xtevent/pull/197, but then reverted in https://github.com/JMSLab/xtevent/commit/d6c899e43cdcd5031816fb031016749e0e955b1f. We now create a second linked branch to re-make intended changes in this issue. Then, we'are opening a new PR to revise and merge changes to main.

**Comment by Constantino-Carreto-Romero** [comment]
@jorpppp 
in https://github.com/JMSLab/xtevent/commit/c14ff42ed4ef5bce0a9ed7207fb7b671e1172e6e I have pushed the changes from the previous commits https://github.com/JMSLab/xtevent/commit/5e020902f73ce5712072791ca5870399846edae4 and https://github.com/JMSLab/xtevent/commit/95662b9c160fc1131652414dfa13f6c07810244 and in https://github.com/JMSLab/xtevent/commit/533fa22b1ee07390d4fdcdac598d55182f9c0eba the changes from https://github.com/JMSLab/xtevent/commit/3548c5aa46542438eb932abb8f18d69f640a365e.

**Comment by Constantino-Carreto-Romero** [comment]
Summary: In this issue, we added the `replace` suboption to `savek`.
Thread continues in https://github.com/JMSLab/xtevent/pull/201
